### ISSUE TITLE
Support xarray coordinates

### ISSUE THREAD

**Issue by markspec** [TGSAI/mdio-cpp#3]
Constructor should allow support for non-dimensional coordinates in a manner compatible with xarray.

This required coordinates to be added to .zmetadata and DATA/.zattrs

**Comment by BrianMichell** [comment]
Constructor support for [coordinates](https://mdio-python.readthedocs.io/en/v1-new-schema/data_models/version_1.html#mdio.schemas.v1.variable.Variable.coordinates) is supported. The C++ API support for coordinate usage is not well defined yet.
